name: Static Analysis
on: [push, pull_request, workflow_dispatch]
jobs:
  detekt:
    name: Detekt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Run Detekt
        run: ./gradlew detekt
  android_lint:
    name: Android Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Lint
        run: ./gradlew lint
  build_main_and_current:
    name: Build Main Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Assemble Release AAR
        run: ./gradlew clean assembleRelease
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Main Card AAR
          path: Card/build/outputs/aar/Card-release.aar
    name: Build Current Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@v2
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Assemble Release AAR
        run: ./gradlew clean assembleRelease
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Current Card AAR
          path: Card/build/outputs/aar/Card-release.aar
  diffuse:
    name: Diffuse AAR Analysis
    runs-on: macOS-11
    steps:
      - run: brew install JakeWharton/repo/diffuse
