name: Static Analysis
on: [pull_request, workflow_dispatch]
jobs:
  detekt:
    name: Detekt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'microsoft'
      - name: Run Detekt
        run: ./gradlew detekt

  android_lint:
    name: Android Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'microsoft'
      - name: Lint
        run: ./gradlew lint

  diffuse:
    name: Diffuse AAR Analysis
    runs-on: macOS-11
    steps:
      # Set up environment to assemble SDK
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'microsoft'

      # Assemble artifacts from main branch
      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Assemble Release AAR on Main Branch
        run: ./gradlew clean assembleRelease
      - name: Upload Main Branch Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: main-aar
          path: |
            Core/build/outputs/aar/Core-release.aar
            Card/build/outputs/aar/Card-release.aar
            PayPalCheckout/build/outputs/aar/PayPalCheckout-release.aar

      # Assemble artifacts from current branch
      - name: Checkout Current Branch
        uses: actions/checkout@v2
      - name: Assemble Release AAR on Current Branch
        run: ./gradlew clean assembleRelease
      - name: Upload Current Branch Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: current-aar
          path: |
            Core/build/outputs/aar/Core-release.aar
            Card/build/outputs/aar/Card-release.aar
            PayPalCheckout/build/outputs/aar/PayPalCheckout-release.aar

      # Set up Diffuse
      - name: Install Diffuse
        run: brew install JakeWharton/repo/diffuse
      - name: Download Workflow Artifacts 
        uses: actions/download-artifact@v2
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '11'

      # Run Diffuse analysis
      - name: Run Diffuse Analysis - Card
        run: diffuse diff --aar main-aar/Card/build/outputs/aar/Card-release.aar current-aar/Card/build/outputs/aar/Card-release.aar
      - name: Run Diffuse Analysis - Core
        run: diffuse diff --aar main-aar/Core/build/outputs/aar/Core-release.aar current-aar/Core/build/outputs/aar/Core-release.aar
      - name: Run Diffuse Analysis - PayPal
        run: diffuse diff --aar main-aar/PayPalCheckout/build/outputs/aar/PayPalCheckout-release.aar current-aar/PayPalCheckout/build/outputs/aar/PayPalCheckout-release.aar
