name: Static Analysis
on: [push, workflow_dispatch]
jobs:
  detekt:
    name: Detekt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Run Detekt
        run: ./gradlew detekt
        uses: actions/upload-artifact@v2
        with:
          name: detekt-output
          path: build/reports/
