name: Tests
on: [push]
jobs:
  unit_test_job:
    name: Unit Tests
    runs-on: macOS-11
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Run Unit Tests
        run: ./gradlew --stacktrace testRelease